[16:53:34:321] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleMethodArgumentNoValidException(GlobalExceptionHandler.java:60) - MethodArgumentNotValidException: org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [1] in public com.arbor.mall.common.ApiRestResponse com.arbor.mall.controller.CategoryController.addCategory(javax.servlet.http.HttpSession,com.arbor.mall.model.request.AddCategoryReq): [Field error in object 'addCategoryReq' on field 'name': rejected value [精选牛肉切片]; codes [Size.addCategoryReq.name,Size.name,Size.java.lang.String,Size]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [addCategoryReq.name,name]; arguments []; default message [name],5,2]; default message [个数必须在2和5之间]] 
[16:53:55:344] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleMethodArgumentNoValidException(GlobalExceptionHandler.java:60) - MethodArgumentNotValidException: org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [1] in public com.arbor.mall.common.ApiRestResponse com.arbor.mall.controller.CategoryController.addCategory(javax.servlet.http.HttpSession,com.arbor.mall.model.request.AddCategoryReq) with 2 errors: [Field error in object 'addCategoryReq' on field 'name': rejected value [精选牛肉切片]; codes [Size.addCategoryReq.name,Size.name,Size.java.lang.String,Size]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [addCategoryReq.name,name]; arguments []; default message [name],5,2]; default message [个数必须在2和5之间]] [Field error in object 'addCategoryReq' on field 'type': rejected value [5]; codes [Max.addCategoryReq.type,Max.type,Max.java.lang.Integer,Max]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [addCategoryReq.type,type]; arguments []; default message [type],3]; default message [最大不能超过3]] 
[16:54:06:057] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleMethodArgumentNoValidException(GlobalExceptionHandler.java:60) - MethodArgumentNotValidException: org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [1] in public com.arbor.mall.common.ApiRestResponse com.arbor.mall.controller.CategoryController.addCategory(javax.servlet.http.HttpSession,com.arbor.mall.model.request.AddCategoryReq) with 3 errors: [Field error in object 'addCategoryReq' on field 'type': rejected value [5]; codes [Max.addCategoryReq.type,Max.type,Max.java.lang.Integer,Max]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [addCategoryReq.type,type]; arguments []; default message [type],3]; default message [最大不能超过3]] [Field error in object 'addCategoryReq' on field 'name': rejected value [精选牛肉切片]; codes [Size.addCategoryReq.name,Size.name,Size.java.lang.String,Size]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [addCategoryReq.name,name]; arguments []; default message [name],5,2]; default message [个数必须在2和5之间]] [Field error in object 'addCategoryReq' on field 'parentId': rejected value [null]; codes [NotNull.addCategoryReq.parentId,NotNull.parentId,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [addCategoryReq.parentId,parentId]; arguments []; default message [parentId]]; default message [上级目录ID不能为空]] 
[16:54:21:565] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleArborMallException(GlobalExceptionHandler.java:47) - ArborMallException: com.arbor.mall.exception.ArborMallException: 不允许重名
[17:11:21:187] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleArborMallException(GlobalExceptionHandler.java:47) - ArborMallException: com.arbor.mall.exception.ArborMallException: 不允许重名
[17:11:31:572] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleArborMallException(GlobalExceptionHandler.java:47) - ArborMallException: com.arbor.mall.exception.ArborMallException: 不允许重名
[18:50:39:705] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleArborMallException(GlobalExceptionHandler.java:47) - ArborMallException: com.arbor.mall.exception.ArborMallException: 不允许重名
[19:26:27:727] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleArborMallException(GlobalExceptionHandler.java:47) - ArborMallException: com.arbor.mall.exception.ArborMallException: 删除失败
[20:46:09:649] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleException(GlobalExceptionHandler.java:35) - Default Exception: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (arbor_mall_datasource) has been closed.
### The error may exist in file [E:\IdeaProjects\Projects\mall\target\classes\mappers\CategoryMapper.xml]
### The error may involve com.arbor.mall.model.dao.CategoryMapper.selectCategoryByParentId
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (arbor_mall_datasource) has been closed.
[20:51:07:475] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleException(GlobalExceptionHandler.java:35) - Default Exception: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (arbor_mall_datasource) has been closed.
### The error may exist in file [E:\IdeaProjects\Projects\mall\target\classes\mappers\CategoryMapper.xml]
### The error may involve com.arbor.mall.model.dao.CategoryMapper.selectCategoryByParentId
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (arbor_mall_datasource) has been closed.
[20:54:24:967] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleException(GlobalExceptionHandler.java:35) - Default Exception: java.lang.NullPointerException
[20:58:59:988] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleException(GlobalExceptionHandler.java:35) - Default Exception: java.lang.NullPointerException
[21:00:55:919] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleException(GlobalExceptionHandler.java:35) - Default Exception: java.lang.NullPointerException
[21:01:16:148] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleException(GlobalExceptionHandler.java:35) - Default Exception: java.lang.NullPointerException
[21:04:13:049] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleException(GlobalExceptionHandler.java:35) - Default Exception: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.StackOverflowError
[21:12:12:462] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleException(GlobalExceptionHandler.java:35) - Default Exception: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (arbor_mall_datasource) has been closed.
### The error may exist in file [E:\IdeaProjects\Projects\mall\target\classes\mappers\CategoryMapper.xml]
### The error may involve com.arbor.mall.model.dao.CategoryMapper.selectCategoryByParentId
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (arbor_mall_datasource) has been closed.
[21:26:56:685] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleException(GlobalExceptionHandler.java:35) - Default Exception: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (arbor_mall_datasource) has been closed.
### The error may exist in file [E:\IdeaProjects\Projects\mall\target\classes\mappers\CategoryMapper.xml]
### The error may involve com.arbor.mall.model.dao.CategoryMapper.selectCategoryByParentId
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (arbor_mall_datasource) has been closed.
[22:55:28:881] [ERROR] - com.arbor.mall.exception.GlobalExceptionHandler.handleException(GlobalExceptionHandler.java:35) - Default Exception: org.springframework.data.redis.serializer.SerializationException: Cannot serialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: com.arbor.mall.model.vo.CategoryVO
